<?xml version="1.0" encoding="utf-8"?>
<!-- edited with XMLSpy v2011 sp1 (http://www.altova.com) by End User (free.org) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="AnagraficaClienteFornitore" type="AnagraficaClienteFornitore" nillable="true"/>
	<xs:complexType name="AnagraficaClienteFornitore">
		<xs:sequence>
			<xs:element name="DatiIdentificativi" type="DatiIdentificativi" minOccurs="0" maxOccurs="1"/>
			<xs:element name="SedePrincipale" type="SedePrincipale" minOccurs="0" maxOccurs="1"/>
			<xs:element name="UlterioreSede" type="UlterioreSede" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="DatiIdentificativi">
		<xs:sequence>
			<xs:element name="Codice" minOccurs="0" maxOccurs="1">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="12"/>
						<xs:minLength value="3"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="CodPaesePartitaIVa" minOccurs="0" maxOccurs="1">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="2"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="PartitaIva" minOccurs="0" maxOccurs="1">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="12"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="CodiceFiscale" minOccurs="0" maxOccurs="1">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="16"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Denominazione" minOccurs="0" maxOccurs="1">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="255"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="RagSocCognome" minOccurs="0" maxOccurs="1">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="255"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Nome" minOccurs="0" maxOccurs="1">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="50"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="SedePrincipale">
		<xs:sequence>
			<xs:element name="Sede" type="Sede" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Sede">
		<xs:sequence>
			<xs:element name="SedeEstera" type="xs:boolean" minOccurs="1" maxOccurs="1"/>
			<xs:element name="Indirizzo" minOccurs="0" maxOccurs="1">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="255"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="NumeroCivico" minOccurs="0" maxOccurs="1">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="50"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Cap" minOccurs="0" maxOccurs="1">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="5"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Comune" minOccurs="0" maxOccurs="1">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="50"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Provincia" minOccurs="0" maxOccurs="1">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="2"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Nazione" minOccurs="0" maxOccurs="1">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="255"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Referente" minOccurs="0" maxOccurs="1">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="255"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Telefono" minOccurs="0" maxOccurs="1">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="150"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Telefono2" minOccurs="0" maxOccurs="1">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="150"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Fax" minOccurs="0" maxOccurs="1">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="150"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Fax2" minOccurs="0" maxOccurs="1">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="150"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Pec" minOccurs="0" maxOccurs="1">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="255"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Email" minOccurs="0" maxOccurs="1">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="255"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Email2" minOccurs="0" maxOccurs="1">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="255"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="UlterioreSede">
		<xs:sequence>
			<xs:element name="ListaUlterioriSedi" type="ArrayOfSede" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ArrayOfSede">
		<xs:sequence>
			<xs:element name="Sede" type="Sede" nillable="true" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="ContCoUI" type="ContCoUI" nillable="true"/>
	<xs:complexType name="ContCoUI">
		<xs:sequence>
			<xs:element name="Id" type="xs:long" minOccurs="1" maxOccurs="1"/>
			<xs:element name="Codice" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="Desc" type="xs:string" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="ArrayOfContCoUI" type="ArrayOfContCoUI" nillable="true"/>
	<xs:complexType name="ArrayOfContCoUI">
		<xs:sequence>
			<xs:element name="ContCoUI" type="ContCoUI" nillable="true" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="ColonneImportazioneEstrattoConto" type="ColonneImportazioneEstrattoConto" nillable="true"/>
	<xs:complexType name="ColonneImportazioneEstrattoConto">
		<xs:sequence>
			<xs:element name="Id" type="xs:int" minOccurs="1" maxOccurs="1"/>
			<xs:element name="Nome" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="Descrizione" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="Ordine" type="xs:short" minOccurs="1" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="ResponseIsImportabilePrimaNota" type="ResponseIsImportabilePrimaNota"/>
	<xs:simpleType name="ResponseIsImportabilePrimaNota">
		<xs:restriction base="xs:string">
			<xs:enumeration value="NonControllato"/>
			<xs:enumeration value="CliFornNonSelezionato"/>
			<xs:enumeration value="CliFornCodiceGbMancante"/>
			<xs:enumeration value="CliFornCodiceMancanteInXml"/>
			<xs:enumeration value="CausaleIvaTotaleDiversoDaTotaleDocumento"/>
			<xs:enumeration value="CausaliIvaMancanti"/>
			<xs:enumeration value="CausaliIvaDiversaDaTipologiaPrimaNota"/>
			<xs:enumeration value="CausaliIvaMancantiNelFileDiOrigine"/>
			<xs:enumeration value="CausaleContabileMancanteXML"/>
			<xs:enumeration value="CausaleContabileNonImpostata"/>
			<xs:enumeration value="CausaleContabileDiversaDaTipologiaPrimaNota"/>
			<xs:enumeration value="ContoMancante"/>
			<xs:enumeration value="ContiErratiDAoImporti"/>
			<xs:enumeration value="SaldoDiversoDaZero"/>
			<xs:enumeration value="OK"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="ProvenienzaModificaPrimaNota" type="ProvenienzaModificaPrimaNota"/>
	<xs:simpleType name="ProvenienzaModificaPrimaNota">
		<xs:restriction base="xs:string">
			<xs:enumeration value="DaSezioneIva"/>
			<xs:enumeration value="DaSezioneConto"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="DatiIdentificativi" type="DatiIdentificativi" nillable="true"/>
	<xs:element name="Sede" type="Sede" nillable="true"/>
	<xs:element name="SedeDec" type="SedeDec" nillable="true"/>
	<xs:complexType name="SedeDec" mixed="false">
		<xs:complexContent mixed="false">
			<xs:extension base="Sede">
				<xs:sequence>
					<xs:element name="Id" type="xs:int" minOccurs="1" maxOccurs="1"/>
					<xs:element name="IdXml_DatiIdentificativi" type="xs:int" minOccurs="1" maxOccurs="1"/>
					<xs:element name="IsSedePrincipale" type="xs:short" minOccurs="1" maxOccurs="1"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name="SedePrincipale" type="SedePrincipale" nillable="true"/>
	<xs:element name="UlterioreSede" type="UlterioreSede" nillable="true"/>
	<xs:element name="PrimaNotaXsd" type="PrimaNotaXsd" nillable="true"/>
	<xs:complexType name="PrimaNotaXsd">
		<xs:sequence>
			<xs:element name="ListaAnagraficaClienteFornitore" type="ArrayOfAnagraficaClienteFornitore" minOccurs="0" maxOccurs="1"/>
			<xs:element name="ListaPrimaNota" type="ArrayOfPrimaNotaImportazione" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ArrayOfAnagraficaClienteFornitore">
		<xs:sequence>
			<xs:element name="AnagraficaClienteFornitore" type="AnagraficaClienteFornitore" nillable="true" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ArrayOfPrimaNotaImportazione">
		<xs:sequence>
			<xs:element name="PrimaNotaImportazione" type="PrimaNotaImportazione" nillable="true" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="PrimaNotaImportazione">
		<xs:choice>
			<xs:element name="PrimaNotaIva" type="PrimaNotaImportazioneIva" minOccurs="0" maxOccurs="1"/>
			<xs:element name="PrimaNotaNonIva" type="PrimaNotaImportazioneNonIva" minOccurs="0" maxOccurs="1"/>
		</xs:choice>
	</xs:complexType>
	<xs:complexType name="PrimaNotaImportazioneIva">
		<xs:sequence>
			<xs:element name="PrimaNotaDatiGenerici" type="PrimaNotaDatiGenerici" minOccurs="0" maxOccurs="1"/>
			<xs:element name="PrimaNotaSezioneIva" type="SezioneIva" minOccurs="0" maxOccurs="1"/>
			<xs:element name="PrimaNotaSezioneConto" type="SezioneConto" minOccurs="0" maxOccurs="1"/>
			<xs:element name="PrimaNotaSezionePagamento" type="SezionePagamento" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="PrimaNotaDatiGenerici">
		<xs:sequence>
			<xs:element name="TipologiaDocumentoIva" type="TipologiaDocumentoIva" minOccurs="1" maxOccurs="1"/>
			<xs:element name="CodiceCliente" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="CausaleContabile" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="NumeroDocumento" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="DataDocumento" type="xs:date" minOccurs="1" maxOccurs="1"/>
			<xs:element name="DataRegistrazione" type="xs:date" minOccurs="1" maxOccurs="1"/>
			<xs:element name="NumeroRegistroIva" type="xs:int" minOccurs="1" maxOccurs="1"/>
			<xs:element name="NumeroRegistroIvaString" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="ProtocolloIva" type="xs:int" minOccurs="1" maxOccurs="1"/>
			<xs:element name="TotaleDocumento" nillable="false" minOccurs="1" maxOccurs="1">
				<xs:simpleType>
					<xs:restriction base="xs:double">
						<xs:minInclusive value="0"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="TipologiaDocumentoIva">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Acquisto"/>
			<xs:enumeration value="Vendita"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="SezioneIva">
		<xs:sequence>
			<xs:element name="ListaDettaglioSezioneIva" type="ArrayOfSezioneIvaDettaglio" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ArrayOfSezioneIvaDettaglio">
		<xs:sequence>
			<xs:element name="SezioneIvaDettaglio" type="SezioneIvaDettaglio" nillable="true" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="SezioneIvaDettaglio">
		<xs:sequence>
			<xs:element name="CausaleIva" minOccurs="0" maxOccurs="1">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="255"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Imponibile" type="xs:double" minOccurs="1" maxOccurs="1"/>
			<xs:element name="Imposta" type="xs:double" minOccurs="1" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="SezioneConto">
		<xs:sequence>
			<xs:element name="ListaDettaglioSezioneConto" type="ArrayOfSezioneContoDettaglio" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ArrayOfSezioneContoDettaglio">
		<xs:sequence>
			<xs:element name="SezioneContoDettaglio" type="SezioneContoDettaglio" nillable="true" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="SezioneContoDettaglio">
		<xs:sequence>
			<xs:element name="Conto" minOccurs="0" maxOccurs="1">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="255"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="ImponibileConto" type="xs:double" minOccurs="1" maxOccurs="1"/>
			<xs:element name="IsRitenutaAcconto" type="xs:boolean" minOccurs="1" maxOccurs="1"/>
			<xs:element name="Descrizione" minOccurs="0" maxOccurs="1">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="255"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="SezionePagamento">
		<xs:sequence>
			<xs:element name="ListaPagamentoDettaglio" type="ArrayOfPagamentoDettaglio" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ArrayOfPagamentoDettaglio">
		<xs:sequence>
			<xs:element name="PagamentoDettaglio" type="PagamentoDettaglio" nillable="true" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="PagamentoDettaglio">
		<xs:sequence>
			<xs:element name="Data" type="xs:date" minOccurs="1" maxOccurs="1"/>
			<xs:element name="NumeroDocumento" minOccurs="0" maxOccurs="1">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="50"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Conto" minOccurs="0" maxOccurs="1">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="255"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Importo" type="xs:double" minOccurs="1" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="PrimaNotaImportazioneNonIva">
		<xs:sequence>
			<xs:element name="PrimaNotaDatiGenerici" type="PrimaNotaDatiGenericiNonIva" minOccurs="0" maxOccurs="1"/>
			<xs:element name="PrimaNotaSezioneConto" type="SezioneContoNonIva" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="PrimaNotaDatiGenericiNonIva">
		<xs:sequence>
			<xs:element name="CausaleContabile" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="NumeroDocumento" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="DataDocumento" type="xs:date" minOccurs="1" maxOccurs="1"/>
			<xs:element name="DataRegistrazione" type="xs:date" minOccurs="1" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="SezioneContoNonIva">
		<xs:sequence>
			<xs:element name="ListaDettaglioSezioneConto" type="ArrayOfSezioneContoDettaglioNonIva" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ArrayOfSezioneContoDettaglioNonIva">
		<xs:sequence>
			<xs:element name="SezioneContoDettaglioNonIva" type="SezioneContoDettaglioNonIva" nillable="true" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="SezioneContoDettaglioNonIva">
		<xs:sequence>
			<xs:element name="Conto" minOccurs="0" maxOccurs="1">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="255"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="ImponibileConto" type="xs:double" minOccurs="1" maxOccurs="1"/>
			<xs:element name="Descrizione" minOccurs="0" maxOccurs="1">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="255"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="PagamentoDettaglio" type="PagamentoDettaglio" nillable="true"/>
	<xs:element name="PagamentoDettaglioDec" type="PagamentoDettaglioDec" nillable="true"/>
	<xs:complexType name="PagamentoDettaglioDec" mixed="false">
		<xs:complexContent mixed="false">
			<xs:extension base="PagamentoDettaglio">
				<xs:sequence>
					<xs:element name="StrIntestazionePrimaNotaProvenienza" type="xs:string" minOccurs="0" maxOccurs="1"/>
					<xs:element name="Seleziona" type="xs:boolean" minOccurs="1" maxOccurs="1"/>
					<xs:element name="Forzato" type="xs:boolean" minOccurs="1" maxOccurs="1"/>
					<xs:element name="ContoGB" type="xs:string" minOccurs="0" maxOccurs="1"/>
					<xs:element name="DescrizioneContoGB" type="xs:string" minOccurs="0" maxOccurs="1"/>
					<xs:element name="Id" type="xs:int" minOccurs="1" maxOccurs="1"/>
					<xs:element name="IdXml_PrimaNotaDatiGenerici" type="xs:int" minOccurs="1" maxOccurs="1"/>
					<xs:element name="IntForzato" type="xs:short" minOccurs="1" maxOccurs="1"/>
					<xs:element name="StrData" type="xs:string" minOccurs="0" maxOccurs="1"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name="PrimaNotaDatiGenericiNonIva" type="PrimaNotaDatiGenericiNonIva" nillable="true"/>
	<xs:element name="PrimaNotaImportazione" type="PrimaNotaImportazione" nillable="true"/>
	<xs:element name="PrimaNotaDatiGenerici" type="PrimaNotaDatiGenerici" nillable="true"/>
	<xs:element name="PrimaNotaImportazioneDec" type="PrimaNotaImportazioneDec" nillable="true"/>
	<xs:complexType name="PrimaNotaImportazioneDec" mixed="false">
		<xs:complexContent mixed="false">
			<xs:extension base="PrimaNotaImportazione">
				<xs:sequence>
					<xs:element name="TipologiaDocumento" type="TipologiaDocumento" minOccurs="1" maxOccurs="1"/>
					<xs:element name="Id" type="xs:int" minOccurs="1" maxOccurs="1"/>
					<xs:element name="Seleziona" type="xs:boolean" minOccurs="1" maxOccurs="1"/>
					<xs:element name="CoForzata" type="xs:boolean" minOccurs="1" maxOccurs="1"/>
					<xs:element name="IdCo" type="xs:int" minOccurs="1" maxOccurs="1"/>
					<xs:element name="CoCod" type="xs:string" minOccurs="0" maxOccurs="1"/>
					<xs:element name="CoDesc" type="xs:string" minOccurs="0" maxOccurs="1"/>
					<xs:element name="ListaSezioneIvaDettaglioDec" type="ArrayOfSezioneIvaDettaglioDec" minOccurs="0" maxOccurs="1"/>
					<xs:element name="ListaSezioneContoDettaglioDec" type="ArrayOfSezioneContoDettaglioDec" minOccurs="0" maxOccurs="1"/>
					<xs:element name="ListaSezionePagamentoDettaglioDec" type="ArrayOfPagamentoDettaglioDec" minOccurs="0" maxOccurs="1"/>
					<xs:element name="IntCoForzato" type="xs:short" minOccurs="1" maxOccurs="1"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:simpleType name="TipologiaDocumento">
		<xs:restriction base="xs:string">
			<xs:enumeration value="IvaAcquisto"/>
			<xs:enumeration value="IvaVendita"/>
			<xs:enumeration value="NonIva"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="ArrayOfSezioneIvaDettaglioDec">
		<xs:sequence>
			<xs:element name="SezioneIvaDettaglioDec" type="SezioneIvaDettaglioDec" nillable="true" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="SezioneIvaDettaglioDec" mixed="false">
		<xs:complexContent mixed="false">
			<xs:extension base="SezioneIvaDettaglio">
				<xs:sequence>
					<xs:element name="Forzato" type="xs:boolean" minOccurs="1" maxOccurs="1"/>
					<xs:element name="IdIV" type="xs:int" minOccurs="1" maxOccurs="1"/>
					<xs:element name="CodIv" type="xs:string" minOccurs="0" maxOccurs="1"/>
					<xs:element name="DescIv" type="xs:string" minOccurs="0" maxOccurs="1"/>
					<xs:element name="Id" type="xs:int" minOccurs="1" maxOccurs="1"/>
					<xs:element name="IdXml_PrimaNotaDatiGenerici" type="xs:int" minOccurs="1" maxOccurs="1"/>
					<xs:element name="IntForzato" type="xs:short" minOccurs="1" maxOccurs="1"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="ArrayOfSezioneContoDettaglioDec">
		<xs:sequence>
			<xs:element name="SezioneContoDettaglioDec" type="SezioneContoDettaglioDec" nillable="true" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="SezioneContoDettaglioDec" mixed="false">
		<xs:complexContent mixed="false">
			<xs:extension base="SezioneContoDettaglio">
				<xs:sequence>
					<xs:element name="Forzato" type="xs:boolean" minOccurs="1" maxOccurs="1"/>
					<xs:element name="ContoGB" type="xs:string" minOccurs="0" maxOccurs="1"/>
					<xs:element name="DescrizioneContoGB" type="xs:string" minOccurs="0" maxOccurs="1"/>
					<xs:element name="ImponibileVideo" type="xs:double" minOccurs="1" maxOccurs="1"/>
					<xs:element name="Dare" type="xs:boolean" minOccurs="1" maxOccurs="1"/>
					<xs:element name="Avere" type="xs:boolean" minOccurs="1" maxOccurs="1"/>
					<xs:element name="Id" type="xs:int" minOccurs="1" maxOccurs="1"/>
					<xs:element name="IdXml_PrimaNotaDatiGenerici" type="xs:int" minOccurs="1" maxOccurs="1"/>
					<xs:element name="IntForzato" type="xs:short" minOccurs="1" maxOccurs="1"/>
					<xs:element name="IntIsRitenutaAcconto" type="xs:short" minOccurs="1" maxOccurs="1"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="ArrayOfPagamentoDettaglioDec">
		<xs:sequence>
			<xs:element name="PagamentoDettaglioDec" type="PagamentoDettaglioDec" nillable="true" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="PrimaNotaImportazioneIva" type="PrimaNotaImportazioneIva" nillable="true"/>
	<xs:element name="PrimaNotaImportazioneNonIva" type="PrimaNotaImportazioneNonIva" nillable="true"/>
	<xs:element name="SezioneConto" type="SezioneConto" nillable="true"/>
	<xs:element name="SezioneContoDettaglio" type="SezioneContoDettaglio" nillable="true"/>
	<xs:element name="SezioneContoDettaglioDec" type="SezioneContoDettaglioDec" nillable="true"/>
	<xs:element name="SezioneContoDettaglioNonIva" type="SezioneContoDettaglioNonIva" nillable="true"/>
	<xs:element name="SezioneContoNonIva" type="SezioneContoNonIva" nillable="true"/>
	<xs:element name="SezioneIva" type="SezioneIva" nillable="true"/>
	<xs:element name="SezioneIvaDettaglio" type="SezioneIvaDettaglio" nillable="true"/>
	<xs:element name="SezioneIvaDettaglioDec" type="SezioneIvaDettaglioDec" nillable="true"/>
	<xs:element name="SezionePagamento" type="SezionePagamento" nillable="true"/>
	<xs:element name="PrimaNota" type="PrimaNota" nillable="true"/>
	<xs:complexType name="PrimaNota"/>
</xs:schema>
